# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import userdata
open_api_key = userdata.get('OPENAI_API_KEY')

import openai

!pip install openai==0.28

!pip show openai

openai.api_key = open_api_key

import pandas as pd
pd.DataFrame(openai.Model.list()['data'])

"""#ChatCompletion API and Completion API

* Completion API: Hooks you up with text completions from a single prompt
* Chat Completion API : Nails it in the chat game , keeping the conversational flow intact

#ChatCompletion API
"""

import openai
prompt = "Who won the world cup in 1991?"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ]
)

print(response)

"""#get just content"""

import openai
prompt = "Who won the world cup in 1991?"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ]
)

print(response.choices[0].message.content)

"""#ChatCompletion API"""

#chatCompletion api
prompt1 = "Hello How are you?"
prompt2 = "I am 23 years old & I am a Programmer"
prompt3 = "Tell me about me"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt1},
        {"role": "user", "content": prompt2},
        {"role": "user", "content": prompt3}
    ]
)

print(response.choices[0].message.content)

"""#add parameter

* app openai tokenizer
"""

prompt = "What is Python?"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ],

    max_token = 25 # output will 25 token
)

print(response["choices"][0]['message']['content'])

"""#add parameter

* app openai temperature

| Temperature | AI এর আচরণ (Behavior)                                  | ব্যবহার/উদাহরণ                             |
| ----------- | ------------------------------------------------------ | ------------------------------------------ |
| **0.1**     | খুব predictable, প্রায় সবসময় একই উত্তর দেয়          | ফ্যাক্ট চেকিং, কোড জেনারেশন, ডেটা summary  |
| **0.2**     | একদম কম randomness, কিছুটা variation                   | short factual explanations                 |
| **0.3**     | কম randomness, বেশি structured উত্তর                   | QA, simple instructions                    |
| **0.4**     | হালকা creativity, কিছু ভিন্নতা                         | casual conversation, light content writing |
| **0.5**     | moderate creativity, একই প্রশ্নে মাঝে মাঝে আলাদা উত্তর | general Q&A, explanations, ideas           |
| **0.6**     | আরও creative, কিছু নতুন variation, তবে controlled      | short story, poem, brainstorming           |
"""

prompt = "What is Python?"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ],

   temperature = 0.6  #createvity response parameter
   n = 2 # get two responsed
)

print(response["choices"][0]['message']['content'])

prompt = "Give me the sentiment of this sentence: This Movie is Amazing!"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ],

    temperature = 0.6  #createvity response parameter
)

print(response["choices"][0]['message']['content'])

prompt = "Give me a Python code to add 2 numbers"

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a kind helpful assistant."},
        {"role": "user", "content": prompt}
    ],

    temperature = 0.6  #createvity response parameter
)

print(response["choices"][0]['message']['content'])

"""#Completion API"""

prompt = "What is Python?"
response = openai.Completion.create(
   model = "babbage-002",
   prompt = prompt

)
print(response)